### ISSUE TITLE
Overriding tags.html does not output meta content

### ISSUE THREAD

**Issue by gscr** [neon-jungle/wagtail-metadata#44]
When I try to override the `wagtailmetadata/parts/tags.html` template I can display the content of my custom meta tags but all the default tags output `content=""` or `content=" - "`
### Setup
django 2.0.3
wagtail 2.0
wagtail-metadata 2.0.0

**Comment by KalobTaulien** [comment]
You may need to look at your wagtail page settings, or the settings in your cms admin area. I'm using wagtail 2.10.2 and have overwritten the tags successfully.
