### ISSUE TITLE
wagtail==1.13.1 and wagtail-metadata==0.4.1 not working

### ISSUE THREAD

**Issue by sowinski** [neon-jungle/wagtail-metadata#46]
Hi,

I am using:
wagtail==1.13.1
wagtail-metadata==0.4.1
python 2.7.6

And I'm getting the following exception when adding MetadataPageMixin to my "page":

AttributeError at /
'OneToOneField' object has no attribute 'model'

Any idea why this is happening?

**Comment by seb-b** [comment]
Hi @sowinski, can you include an example of your Page model?
`MetadataPageMixin` doesn't include any `OneToOneField`s
