### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by sowinski** [neon-jungle/wagtail-metadata#47]
Hi,

what is this plugin exactly doing? I tought to get a new tab or something else within wagtail admin to add open graph attributes for facebook etc. 

Can someone describe what this plugin is for?

**Comment by seb-b** [comment]
This plugin adds custom properties to your page models and then lets you output meta attributes using the included template tag. It adds one field to your page models `search_image`.

A good place to start is [MetaPageMixin](https://github.com/takeflight/wagtail-metadata/blob/master/wagtailmetadata/models.py#L44) model for an idea of information that is captured and the [included template](https://github.com/takeflight/wagtail-metadata/blob/master/wagtailmetadata/models.py#L44) for an idea about what is outputted when you use the template tag. 

I realise the description in the readme is a bit vague! I'll try to expand on it at some point
