### ISSUE TITLE
missing search image?

### ISSUE THREAD

**Issue by Pomax** [neon-jungle/wagtail-metadata#50]
We have a bunch of models all of which have the "search image" in the promote tab, but after making a new model that inherits from both the metadata mixin and wagtail's Page, that field is not showing up in the promote tab - is there a way to manually trigger a "metadata check" pass that ensures there is a migration that adds all the metadata fields that should exist to a model that might be missing one (or more)?

**Comment by seb-b** [comment]
The metadata mixin just adds the fields to the model you are extending.

Do you have an example of the model where the field isn't showing up? One thing to be sure of is to put `MetadataPageMixin` before `Page` other wise the `Page`s promote_panels attribute overrides the mixin not vice versa

**Comment by Pomax** [comment]
Yeah, the model we're using that's not showing an image field is https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/models.py#L543, which shows this in its promote tab:

![image](https://user-images.githubusercontent.com/177243/61077626-a8630780-a3d3-11e9-8d90-eea9be8426a7.png)

An example of a page type that works fine is https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/models.py#L417 which shows the follow promote tab content:

![image](https://user-images.githubusercontent.com/177243/61077684-c6c90300-a3d3-11e9-83ab-3561aa66ff22.png)

As far as I can tell, those two models are identical in terms of metadata setup, but while I can find a migration that adds the search image to the `PrimaryPage` class (https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/migrations/0039_auto_20181009_1342.py) no amount of `manage migrate` has added one for the `BlogPage` class.

**Comment by seb-b** [comment]
It'd be worth checking if the database itself or dropping into a django shell and checking the model to see if it has a search image. It looks like it was added in this migration [here](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/migrations/0068_auto_20190509_1803.py), so it should exist. If it doesn't there's a bigger problem here.

It does look like the the `BlogPage` overrides the `promote_panels` attribute which is most likely why the field isn't showing up in the admin.

If you change [this line](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/migrations/0068_auto_20190509_1803.py) to:

```python

promote_panels = FoundationMetadataPageMixin.promote_panels + [
   FieldPanel('tags')
] 
```

That should get you what you want

**Comment by Pomax** [comment]
totally fixed it, thanks so much!
