### ISSUE TITLE
Make meta_tags fail gracefully

### ISSUE THREAD

**Issue by Pomax** [neon-jungle/wagtail-metadata#51]
Just ran into an issue where a base template used for wagtail pages also acted as base template for the absolutely-not-wagtail-managed 404 page, so the base template had this:

```html
{% load i18n wagtailcore_tags wagtailmetadata_tags ... %}

{% get_current_language as lang_code %}

<!DOCTYPE html>
<html lang="{{ lang_code }}">
  <head>
    ...
    {% block watail_metadata %}
      {% meta_tags %}
    {% endblock %}
    ...
  </head>
  <body>
    ...
  </body>
</html>
```

and everything worked fine for normal pages. However, 404 pages using the same base template (so that they look like any other page) don't have any page model backing it, so this code _will_ crash Django, because it's trying to run the `meta_tags` tag for something that doesn't implement the `MetadataPageMixin` class.

Can the `meta_tags` tag be changed to simply output "nothing" when it's run for a context/page that's missing whatever fields from MetadataPageMixin it needs to tap into?

**Comment by bruecksen** [comment]
@Pomax I opened a PR to fix this issue, maybe you could have a look there as well.

**Comment by Pomax** [comment]
Would it be possible to reopen it? "Rewrite the templates" is not how you prevent, or even find out why production crashes =)

**Comment by seb-b** [comment]
@Pomax I've opened #55 which includes error messages for missing models or requests when trying to use the template tags, happy for any feedback.

As explained in the #54, we can't let the meta tags fail silently but hopefully this will at least let the developers know why their pages aren't working as expected when using `meta_tags` improperly.

**Comment by Pomax** [comment]
ah, that's great, thank you!

**Comment by favoyang** [comment]
So it's a good practice to just use `{% if request and self %}{% meta_tags %}{% endif %}` in the base.html? Considering it's actually simpler than overwrite template using blocks.

**Comment by seb-b** [comment]
@favoyang yep, if that works for you that's fine :)

**Comment by favoyang** [comment]
I think it would be worth mentioning it in the docs that if missing the `self` parameter it will fail on like 404 if you put the tag into the base.html, which is hard to find out because Django has a different 404 page for development. And it will break your production deployment easily, and you probably won't notice it either, since people trends to not check the 404 page in their post-deployment verification script.
