### ISSUE TITLE
Don't include site title in Twitter tag by default or make it overrideable

### ISSUE THREAD

**Issue by harrislapiroff** [neon-jungle/wagtail-metadata#56]
This doesn't look good in some use cases, e.g.,

![image](https://user-images.githubusercontent.com/296631/70070249-42189480-15c1-11ea-891d-acf5c3be385b.png)
_Should just be "Donate to Freedom of the Press Foundation" instead of "Donate to Freedom of the Press Foundation — Freedom of..."_

It also can't be changed without overriding the template [tags.html](https://github.com/neon-jungle/wagtail-metadata/blob/master/wagtailmetadata/templates/wagtailmetadata/parts/tags.html). Probably these values should be generated from a page method that can be overridden in a more targeted way. I also think the default behavior should be not to include the site title, but that's potentially more subjective.

**Comment by seb-b** [comment]
Yeah I agree, adding `site_name` to the `meta_title` shouldn't be the default. It's what we usually do internally but it should be done using an override on our side.

**Comment by khashashin** [comment]
Is there any update? Or do you have a temporary workaround to prevent this behavior?

**Comment by seb-b** [comment]
Just released version 3.2.0 that includes a fix for this.

If anyone wants the old behavior back they can override the `get_meta_title`  method to return the title + sitename

**Comment by Pomax** [comment]
Is this now something you can regulate via settings or the like? Because some folks really need the site name in there still =)

**Comment by seb-b** [comment]
No plans to make this a setting, this project is pretty simple with no current config, it'd be nice to keep it that way :)

If you're referencing the mentioned pull request above you could add the following to `wagtailpages/pagemodels/mixin/foundation_metadata.py`

```python
class FoundationMetadataPageMixin(MetadataPageMixin):
   ...
   def get_meta_title(self):
      site = self.get_site()
      title = self.seo_title or self.title
      return f'{title} — {site.site_name}'
```
