### ISSUE TITLE
Consistent quotes in meta tag outputs

### ISSUE THREAD

**Issue by nathan-mcilree** [neon-jungle/wagtail-metadata#63]
Meta tag output uses a mixture of single and double quotes in the template.

<meta itemprop="name" content="{{ object.get_meta_title }}">
<meta itemprop='description' content='{{ object.get_meta_description }}' />

Could all instance be changed to double quotes? Not sure how this process works, can I just issue a pull request?

**Comment by seb-b** [comment]
Yep, feel free to open a pull request to address that, I have no strong opinions on double or single so take your pick :)

**Comment by JoostKiens** [comment]
I noticed this is fixed in master (thanks!), but is not yet available in a release. When will this be released?

**Comment by seb-b** [comment]
woops, had a bit of trouble with the ci pipeline but it's out now in 3.4.1

**Comment by JoostKiens** [comment]
Awesome! Thanks for the quick response @seb-b !
