### ISSUE TITLE
image url is not correct

### ISSUE THREAD

**Issue by marinaWobjects** [neon-jungle/wagtail-metadata#67]
hello ,
i have an issue with image meta .
it's showing the localhost url instead of the server url as shown in this screenshot 
[https://drive.google.com/file/d/1MfXLyuYmUd85YV570gUGjWND295HSdCG/view?usp=sharing](https://drive.google.com/file/d/1MfXLyuYmUd85YV570gUGjWND295HSdCG/view?usp=sharing)

Could u please help ?
thanks in advance,
Matina

**Comment by seb-b** [comment]
The code that generates that url is found [here](https://github.com/neon-jungle/wagtail-metadata/blob/master/wagtailmetadata/models.py#L69)

Is there any references to `127.0.0.1:8001` in your code? It might be an incorrect setting?

**Comment by marinaWobjects** [comment]
the reference for "127.0.0.1:8001" is in the server config not the code 
what do u mean by  incorrect setting?

**Comment by seb-b** [comment]
It might be something to do with your server setup. Perhaps try using the `BASE_URL` setting?

Looks like someone [here](https://stackoverflow.com/questions/58044582/localhost-in-build-absolute-uri-for-django-with-nginx) has a similar problem.

**Comment by MarinaWagih** [comment]
@seb-b  thank u so much this was very helpful 
it's working now

**Comment by seb-b** [comment]
excellent!
