### ISSUE TITLE
Changelog is missing 3.4.1 changes?

### ISSUE THREAD

**Issue by Pomax** [neon-jungle/wagtail-metadata#72]
I'm getting dependabot updates for wagtail-metadata v3.4.1 but there's nothing in the changelog... worth updating the changelog?

**Comment by seb-b** [comment]
it was just this pr to change the quotes to be consistent in the template: https://github.com/neon-jungle/wagtail-metadata/pull/68 

I've update the changlelog :)

**Comment by Pomax** [comment]
cheers. it was more the fact that if you use github's security feature, you get a PR for a version bump with an empty changelog, which is always cause for concern =)
