### ISSUE TITLE
Trailing slash on void elements has no effect and interacts badly with unquoted attribute values.

### ISSUE THREAD

**Issue by aurelien-huet** [neon-jungle/wagtail-metadata#84]
To pass W3C validator it will be interesting to remove trailing slash on meta balise.
<img width="1438" alt="w3c-validator-trailing-slash" src="https://user-images.githubusercontent.com/126562078/221812843-0db922ca-fe5f-4a5a-b780-ab522d7794d6.png">

**Comment by seb-b** [comment]
fixed in 4.0.3, thanks for the contribution!
