### ISSUE TITLE
Slug generation not functioning correctly Wagtail 5.0

### ISSUE THREAD

**Issue by DEWaller** [neon-jungle/wagtail-metadata#89]
Slug generation doesn't appear to functioning correctly on pages inheriting 'MetadataPageMixin'

e.g. Page title: 'My New Home Page', Slug: 'My New Home Page' rather than 'my-new-home-page'

**Comment by seb-b** [comment]
yeah I came across this in another project, looks like wagtail moved the functionality to a widget 
This line: https://github.com/neon-jungle/wagtail-metadata/blob/master/wagtailmetadata/models.py#L94C13-L94C32

Needs to be updated to follow these instructions - https://docs.wagtail.org/en/stable/releases/5.0.html#slug-field-auto-cleaning-now-relies-on-data-attributes

**Comment by DEWaller** [comment]
> yeah I came across this in another project, looks like wagtail moved the functionality to a widget This line: https://github.com/neon-jungle/wagtail-metadata/blob/master/wagtailmetadata/models.py#L94C13-L94C32
> 
> Needs to be updated to follow these instructions - https://docs.wagtail.org/en/stable/releases/5.0.html#slug-field-auto-cleaning-now-relies-on-data-attributes

Thank you, I don't think I would have found that.

I changed the promote_panels to

```
 promote_panels = [
        MultiFieldPanel([
            FieldPanel("slug", widget=SlugInput),
            FieldPanel('seo_title'),
            FieldPanel('show_in_menus'),
            FieldPanel('search_description'),
            FieldPanel('search_image'),
        ], gettext_lazy('Common page configuration')),
    ]
```
and added 

> from wagtail.admin.widgets.slug import SlugInput

**Comment by juliuskiura** [comment]
I had a similar problem and this solution works.
